/*******************************************************************************
 * Participact
 * Copyright 2013-2018 Alma Mater Studiorum - Università di Bologna
 * 
 * This file is part of ParticipAct.
 * 
 * ParticipAct is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 * 
 * ParticipAct is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with ParticipAct. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataInstalledAppsProtos.proto

package it.unibo.participact.domain.proto;

public final class DataInstalledAppsProtos {
	private DataInstalledAppsProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface DataInstalledAppsProtoListOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .proto.DataInstalledAppsProto list = 1;
		java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> getListList();

		it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getList(
				int index);

		int getListCount();

		java.util.List<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> getListOrBuilderList();

		it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder getListOrBuilder(
				int index);
	}

	public static final class DataInstalledAppsProtoList extends
			com.google.protobuf.GeneratedMessage implements
			DataInstalledAppsProtoListOrBuilder {
		// Use DataInstalledAppsProtoList.newBuilder() to construct.
		private DataInstalledAppsProtoList(Builder builder) {
			super(builder);
		}

		private DataInstalledAppsProtoList(boolean noInit) {
		}

		private static final DataInstalledAppsProtoList defaultInstance;

		public static DataInstalledAppsProtoList getDefaultInstance() {
			return defaultInstance;
		}

		public DataInstalledAppsProtoList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable;
		}

		// repeated .proto.DataInstalledAppsProto list = 1;
		public static final int LIST_FIELD_NUMBER = 1;
		private java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> list_;

		public java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> getListList() {
			return list_;
		}

		public java.util.List<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> getListOrBuilderList() {
			return list_;
		}

		public int getListCount() {
			return list_.size();
		}

		public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getList(
				int index) {
			return list_.get(index);
		}

		public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder getListOrBuilder(
				int index) {
			return list_.get(index);
		}

		private void initFields() {
			list_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getListCount(); i++) {
				if (!getList(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < list_.size(); i++) {
				output.writeMessage(1, list_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < list_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, list_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getListFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList build() {
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList buildPartial() {
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList result = new it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList(
						this);
				int from_bitField0_ = bitField0_;
				if (listBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						list_ = java.util.Collections.unmodifiableList(list_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.list_ = list_;
				} else {
					result.list_ = listBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList) {
					return mergeFrom((it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList other) {
				if (other == it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList
						.getDefaultInstance())
					return this;
				if (listBuilder_ == null) {
					if (!other.list_.isEmpty()) {
						if (list_.isEmpty()) {
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureListIsMutable();
							list_.addAll(other.list_);
						}
						onChanged();
					}
				} else {
					if (!other.list_.isEmpty()) {
						if (listBuilder_.isEmpty()) {
							listBuilder_.dispose();
							listBuilder_ = null;
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
							listBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getListFieldBuilder()
									: null;
						} else {
							listBuilder_.addAllMessages(other.list_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getListCount(); i++) {
					if (!getList(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder subBuilder = it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addList(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .proto.DataInstalledAppsProto list = 1;
			private java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> list_ = java.util.Collections
					.emptyList();

			private void ensureListIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto>(
							list_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> listBuilder_;

			public java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> getListList() {
				if (listBuilder_ == null) {
					return java.util.Collections.unmodifiableList(list_);
				} else {
					return listBuilder_.getMessageList();
				}
			}

			public int getListCount() {
				if (listBuilder_ == null) {
					return list_.size();
				} else {
					return listBuilder_.getCount();
				}
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getList(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessage(index);
				}
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.set(index, value);
					onChanged();
				} else {
					listBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.set(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(value);
					onChanged();
				} else {
					listBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(index, value);
					onChanged();
				} else {
					listBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllList(
					java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto> values) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					super.addAll(values, list_);
					onChanged();
				} else {
					listBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearList() {
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder removeList(int index) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.remove(index);
					onChanged();
				} else {
					listBuilder_.remove(index);
				}
				return this;
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder getListBuilder(
					int index) {
				return getListFieldBuilder().getBuilder(index);
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder getListOrBuilder(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> getListOrBuilderList() {
				if (listBuilder_ != null) {
					return listBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(list_);
				}
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder addListBuilder() {
				return getListFieldBuilder()
						.addBuilder(
								it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto
										.getDefaultInstance());
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder addListBuilder(
					int index) {
				return getListFieldBuilder()
						.addBuilder(
								index,
								it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto
										.getDefaultInstance());
			}

			public java.util.List<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder> getListBuilderList() {
				return getListFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder> getListFieldBuilder() {
				if (listBuilder_ == null) {
					listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder, it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder>(
							list_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					list_ = null;
				}
				return listBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataInstalledAppsProtoList)
		}

		static {
			defaultInstance = new DataInstalledAppsProtoList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataInstalledAppsProtoList)
	}

	public interface DataInstalledAppsProtoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int64 sampleTime = 1;
		boolean hasSampleTime();

		long getSampleTime();

		// required string pkg_name = 2;
		boolean hasPkgName();

		String getPkgName();

		// required float version_code = 3;
		boolean hasVersionCode();

		float getVersionCode();

		// required string version_name = 4;
		boolean hasVersionName();

		String getVersionName();

		// required string requested_permissions = 5;
		boolean hasRequestedPermissions();

		String getRequestedPermissions();
	}

	public static final class DataInstalledAppsProto extends
			com.google.protobuf.GeneratedMessage implements
			DataInstalledAppsProtoOrBuilder {
		// Use DataInstalledAppsProto.newBuilder() to construct.
		private DataInstalledAppsProto(Builder builder) {
			super(builder);
		}

		private DataInstalledAppsProto(boolean noInit) {
		}

		private static final DataInstalledAppsProto defaultInstance;

		public static DataInstalledAppsProto getDefaultInstance() {
			return defaultInstance;
		}

		public DataInstalledAppsProto getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_fieldAccessorTable;
		}

		private int bitField0_;
		// required int64 sampleTime = 1;
		public static final int SAMPLETIME_FIELD_NUMBER = 1;
		private long sampleTime_;

		public boolean hasSampleTime() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public long getSampleTime() {
			return sampleTime_;
		}

		// required string pkg_name = 2;
		public static final int PKG_NAME_FIELD_NUMBER = 2;
		private java.lang.Object pkgName_;

		public boolean hasPkgName() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getPkgName() {
			java.lang.Object ref = pkgName_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					pkgName_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getPkgNameBytes() {
			java.lang.Object ref = pkgName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				pkgName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required float version_code = 3;
		public static final int VERSION_CODE_FIELD_NUMBER = 3;
		private float versionCode_;

		public boolean hasVersionCode() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public float getVersionCode() {
			return versionCode_;
		}

		// required string version_name = 4;
		public static final int VERSION_NAME_FIELD_NUMBER = 4;
		private java.lang.Object versionName_;

		public boolean hasVersionName() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public String getVersionName() {
			java.lang.Object ref = versionName_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					versionName_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getVersionNameBytes() {
			java.lang.Object ref = versionName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				versionName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string requested_permissions = 5;
		public static final int REQUESTED_PERMISSIONS_FIELD_NUMBER = 5;
		private java.lang.Object requestedPermissions_;

		public boolean hasRequestedPermissions() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public String getRequestedPermissions() {
			java.lang.Object ref = requestedPermissions_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					requestedPermissions_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getRequestedPermissionsBytes() {
			java.lang.Object ref = requestedPermissions_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				requestedPermissions_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			sampleTime_ = 0L;
			pkgName_ = "";
			versionCode_ = 0F;
			versionName_ = "";
			requestedPermissions_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasSampleTime()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasPkgName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasVersionCode()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasVersionName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasRequestedPermissions()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getPkgNameBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeFloat(3, versionCode_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(4, getVersionNameBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getRequestedPermissionsBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getPkgNameBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeFloatSize(
						3, versionCode_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						4, getVersionNameBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						5, getRequestedPermissionsBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.internal_static_proto_DataInstalledAppsProto_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				sampleTime_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				pkgName_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				versionCode_ = 0F;
				bitField0_ = (bitField0_ & ~0x00000004);
				versionName_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				requestedPermissions_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto build() {
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto buildPartial() {
				it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto result = new it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.sampleTime_ = sampleTime_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.pkgName_ = pkgName_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.versionCode_ = versionCode_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.versionName_ = versionName_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.requestedPermissions_ = requestedPermissions_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto) {
					return mergeFrom((it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto other) {
				if (other == it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto
						.getDefaultInstance())
					return this;
				if (other.hasSampleTime()) {
					setSampleTime(other.getSampleTime());
				}
				if (other.hasPkgName()) {
					setPkgName(other.getPkgName());
				}
				if (other.hasVersionCode()) {
					setVersionCode(other.getVersionCode());
				}
				if (other.hasVersionName()) {
					setVersionName(other.getVersionName());
				}
				if (other.hasRequestedPermissions()) {
					setRequestedPermissions(other.getRequestedPermissions());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasSampleTime()) {

					return false;
				}
				if (!hasPkgName()) {

					return false;
				}
				if (!hasVersionCode()) {

					return false;
				}
				if (!hasVersionName()) {

					return false;
				}
				if (!hasRequestedPermissions()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						sampleTime_ = input.readInt64();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						pkgName_ = input.readBytes();
						break;
					}
					case 29: {
						bitField0_ |= 0x00000004;
						versionCode_ = input.readFloat();
						break;
					}
					case 34: {
						bitField0_ |= 0x00000008;
						versionName_ = input.readBytes();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						requestedPermissions_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int64 sampleTime = 1;
			private long sampleTime_;

			public boolean hasSampleTime() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public long getSampleTime() {
				return sampleTime_;
			}

			public Builder setSampleTime(long value) {
				bitField0_ |= 0x00000001;
				sampleTime_ = value;
				onChanged();
				return this;
			}

			public Builder clearSampleTime() {
				bitField0_ = (bitField0_ & ~0x00000001);
				sampleTime_ = 0L;
				onChanged();
				return this;
			}

			// required string pkg_name = 2;
			private java.lang.Object pkgName_ = "";

			public boolean hasPkgName() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getPkgName() {
				java.lang.Object ref = pkgName_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					pkgName_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setPkgName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				pkgName_ = value;
				onChanged();
				return this;
			}

			public Builder clearPkgName() {
				bitField0_ = (bitField0_ & ~0x00000002);
				pkgName_ = getDefaultInstance().getPkgName();
				onChanged();
				return this;
			}

			void setPkgName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				pkgName_ = value;
				onChanged();
			}

			// required float version_code = 3;
			private float versionCode_;

			public boolean hasVersionCode() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public float getVersionCode() {
				return versionCode_;
			}

			public Builder setVersionCode(float value) {
				bitField0_ |= 0x00000004;
				versionCode_ = value;
				onChanged();
				return this;
			}

			public Builder clearVersionCode() {
				bitField0_ = (bitField0_ & ~0x00000004);
				versionCode_ = 0F;
				onChanged();
				return this;
			}

			// required string version_name = 4;
			private java.lang.Object versionName_ = "";

			public boolean hasVersionName() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public String getVersionName() {
				java.lang.Object ref = versionName_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					versionName_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setVersionName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				versionName_ = value;
				onChanged();
				return this;
			}

			public Builder clearVersionName() {
				bitField0_ = (bitField0_ & ~0x00000008);
				versionName_ = getDefaultInstance().getVersionName();
				onChanged();
				return this;
			}

			void setVersionName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000008;
				versionName_ = value;
				onChanged();
			}

			// required string requested_permissions = 5;
			private java.lang.Object requestedPermissions_ = "";

			public boolean hasRequestedPermissions() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public String getRequestedPermissions() {
				java.lang.Object ref = requestedPermissions_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					requestedPermissions_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setRequestedPermissions(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				requestedPermissions_ = value;
				onChanged();
				return this;
			}

			public Builder clearRequestedPermissions() {
				bitField0_ = (bitField0_ & ~0x00000010);
				requestedPermissions_ = getDefaultInstance()
						.getRequestedPermissions();
				onChanged();
				return this;
			}

			void setRequestedPermissions(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				requestedPermissions_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:proto.DataInstalledAppsProto)
		}

		static {
			defaultInstance = new DataInstalledAppsProto(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataInstalledAppsProto)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataInstalledAppsProtoList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataInstalledAppsProto_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataInstalledAppsProto_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\035DataInstalledAppsProtos.proto\022\005proto\"I"
				+ "\n\032DataInstalledAppsProtoList\022+\n\004list\030\001 \003"
				+ "(\0132\035.proto.DataInstalledAppsProto\"\211\001\n\026Da"
				+ "taInstalledAppsProto\022\022\n\nsampleTime\030\001 \002(\003"
				+ "\022\020\n\010pkg_name\030\002 \002(\t\022\024\n\014version_code\030\003 \002(\002"
				+ "\022\024\n\014version_name\030\004 \002(\t\022\035\n\025requested_perm"
				+ "issions\030\005 \002(\tB<\n!it.unibo.participact.do"
				+ "main.protoB\027DataInstalledAppsProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_proto_DataInstalledAppsProtoList_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_proto_DataInstalledAppsProtoList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataInstalledAppsProtoList_descriptor,
						new java.lang.String[] { "List", },
						it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.class,
						it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProtoList.Builder.class);
				internal_static_proto_DataInstalledAppsProto_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_proto_DataInstalledAppsProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataInstalledAppsProto_descriptor,
						new java.lang.String[] { "SampleTime", "PkgName",
								"VersionCode", "VersionName",
								"RequestedPermissions", },
						it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.class,
						it.unibo.participact.domain.proto.DataInstalledAppsProtos.DataInstalledAppsProto.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
