/*******************************************************************************
 * Participact
 * Copyright 2013-2018 Alma Mater Studiorum - Università di Bologna
 * 
 * This file is part of ParticipAct.
 * 
 * ParticipAct is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 * 
 * ParticipAct is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with ParticipAct. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataLocationProtos.proto

package it.unibo.participact.domain.proto;

public final class DataLocationProtos {
	private DataLocationProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface DataLocationProtoListOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .proto.DataLocationProto list = 1;
		java.util.List<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto> getListList();

		it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto getList(
				int index);

		int getListCount();

		java.util.List<? extends it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder> getListOrBuilderList();

		it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder getListOrBuilder(
				int index);
	}

	public static final class DataLocationProtoList extends
			com.google.protobuf.GeneratedMessage implements
			DataLocationProtoListOrBuilder {
		// Use DataLocationProtoList.newBuilder() to construct.
		private DataLocationProtoList(Builder builder) {
			super(builder);
		}

		private DataLocationProtoList(boolean noInit) {
		}

		private static final DataLocationProtoList defaultInstance;

		public static DataLocationProtoList getDefaultInstance() {
			return defaultInstance;
		}

		public DataLocationProtoList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProtoList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProtoList_fieldAccessorTable;
		}

		// repeated .proto.DataLocationProto list = 1;
		public static final int LIST_FIELD_NUMBER = 1;
		private java.util.List<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto> list_;

		public java.util.List<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto> getListList() {
			return list_;
		}

		public java.util.List<? extends it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder> getListOrBuilderList() {
			return list_;
		}

		public int getListCount() {
			return list_.size();
		}

		public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto getList(
				int index) {
			return list_.get(index);
		}

		public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder getListOrBuilder(
				int index) {
			return list_.get(index);
		}

		private void initFields() {
			list_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getListCount(); i++) {
				if (!getList(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < list_.size(); i++) {
				output.writeMessage(1, list_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < list_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, list_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProtoList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProtoList_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getListFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList build() {
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList buildPartial() {
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList result = new it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList(
						this);
				int from_bitField0_ = bitField0_;
				if (listBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						list_ = java.util.Collections.unmodifiableList(list_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.list_ = list_;
				} else {
					result.list_ = listBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList) {
					return mergeFrom((it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList other) {
				if (other == it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList
						.getDefaultInstance())
					return this;
				if (listBuilder_ == null) {
					if (!other.list_.isEmpty()) {
						if (list_.isEmpty()) {
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureListIsMutable();
							list_.addAll(other.list_);
						}
						onChanged();
					}
				} else {
					if (!other.list_.isEmpty()) {
						if (listBuilder_.isEmpty()) {
							listBuilder_.dispose();
							listBuilder_ = null;
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
							listBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getListFieldBuilder()
									: null;
						} else {
							listBuilder_.addAllMessages(other.list_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getListCount(); i++) {
					if (!getList(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder subBuilder = it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addList(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .proto.DataLocationProto list = 1;
			private java.util.List<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto> list_ = java.util.Collections
					.emptyList();

			private void ensureListIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto>(
							list_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto, it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder, it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder> listBuilder_;

			public java.util.List<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto> getListList() {
				if (listBuilder_ == null) {
					return java.util.Collections.unmodifiableList(list_);
				} else {
					return listBuilder_.getMessageList();
				}
			}

			public int getListCount() {
				if (listBuilder_ == null) {
					return list_.size();
				} else {
					return listBuilder_.getCount();
				}
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto getList(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessage(index);
				}
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.set(index, value);
					onChanged();
				} else {
					listBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.set(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(value);
					onChanged();
				} else {
					listBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(index, value);
					onChanged();
				} else {
					listBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllList(
					java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto> values) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					super.addAll(values, list_);
					onChanged();
				} else {
					listBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearList() {
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder removeList(int index) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.remove(index);
					onChanged();
				} else {
					listBuilder_.remove(index);
				}
				return this;
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder getListBuilder(
					int index) {
				return getListFieldBuilder().getBuilder(index);
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder getListOrBuilder(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder> getListOrBuilderList() {
				if (listBuilder_ != null) {
					return listBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(list_);
				}
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder addListBuilder() {
				return getListFieldBuilder()
						.addBuilder(
								it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto
										.getDefaultInstance());
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder addListBuilder(
					int index) {
				return getListFieldBuilder()
						.addBuilder(
								index,
								it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto
										.getDefaultInstance());
			}

			public java.util.List<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder> getListBuilderList() {
				return getListFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto, it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder, it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder> getListFieldBuilder() {
				if (listBuilder_ == null) {
					listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto, it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder, it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder>(
							list_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					list_ = null;
				}
				return listBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataLocationProtoList)
		}

		static {
			defaultInstance = new DataLocationProtoList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataLocationProtoList)
	}

	public interface DataLocationProtoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int64 sampleTime = 1;
		boolean hasSampleTime();

		long getSampleTime();

		// required double longitude = 2;
		boolean hasLongitude();

		double getLongitude();

		// required double latitude = 3;
		boolean hasLatitude();

		double getLatitude();

		// required double accuracy = 4;
		boolean hasAccuracy();

		double getAccuracy();

		// required string provider = 5;
		boolean hasProvider();

		String getProvider();
	}

	public static final class DataLocationProto extends
			com.google.protobuf.GeneratedMessage implements
			DataLocationProtoOrBuilder {
		// Use DataLocationProto.newBuilder() to construct.
		private DataLocationProto(Builder builder) {
			super(builder);
		}

		private DataLocationProto(boolean noInit) {
		}

		private static final DataLocationProto defaultInstance;

		public static DataLocationProto getDefaultInstance() {
			return defaultInstance;
		}

		public DataLocationProto getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProto_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProto_fieldAccessorTable;
		}

		private int bitField0_;
		// required int64 sampleTime = 1;
		public static final int SAMPLETIME_FIELD_NUMBER = 1;
		private long sampleTime_;

		public boolean hasSampleTime() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public long getSampleTime() {
			return sampleTime_;
		}

		// required double longitude = 2;
		public static final int LONGITUDE_FIELD_NUMBER = 2;
		private double longitude_;

		public boolean hasLongitude() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public double getLongitude() {
			return longitude_;
		}

		// required double latitude = 3;
		public static final int LATITUDE_FIELD_NUMBER = 3;
		private double latitude_;

		public boolean hasLatitude() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public double getLatitude() {
			return latitude_;
		}

		// required double accuracy = 4;
		public static final int ACCURACY_FIELD_NUMBER = 4;
		private double accuracy_;

		public boolean hasAccuracy() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public double getAccuracy() {
			return accuracy_;
		}

		// required string provider = 5;
		public static final int PROVIDER_FIELD_NUMBER = 5;
		private java.lang.Object provider_;

		public boolean hasProvider() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public String getProvider() {
			java.lang.Object ref = provider_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					provider_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getProviderBytes() {
			java.lang.Object ref = provider_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				provider_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			sampleTime_ = 0L;
			longitude_ = 0D;
			latitude_ = 0D;
			accuracy_ = 0D;
			provider_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasSampleTime()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasLongitude()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasLatitude()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasAccuracy()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasProvider()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeDouble(2, longitude_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeDouble(3, latitude_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeDouble(4, accuracy_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getProviderBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeDoubleSize(2, longitude_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeDoubleSize(3, latitude_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream
						.computeDoubleSize(4, accuracy_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						5, getProviderBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProto_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataLocationProtos.internal_static_proto_DataLocationProto_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				sampleTime_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				longitude_ = 0D;
				bitField0_ = (bitField0_ & ~0x00000002);
				latitude_ = 0D;
				bitField0_ = (bitField0_ & ~0x00000004);
				accuracy_ = 0D;
				bitField0_ = (bitField0_ & ~0x00000008);
				provider_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto build() {
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto buildPartial() {
				it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto result = new it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.sampleTime_ = sampleTime_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.longitude_ = longitude_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.latitude_ = latitude_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.accuracy_ = accuracy_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.provider_ = provider_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto) {
					return mergeFrom((it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto other) {
				if (other == it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto
						.getDefaultInstance())
					return this;
				if (other.hasSampleTime()) {
					setSampleTime(other.getSampleTime());
				}
				if (other.hasLongitude()) {
					setLongitude(other.getLongitude());
				}
				if (other.hasLatitude()) {
					setLatitude(other.getLatitude());
				}
				if (other.hasAccuracy()) {
					setAccuracy(other.getAccuracy());
				}
				if (other.hasProvider()) {
					setProvider(other.getProvider());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasSampleTime()) {

					return false;
				}
				if (!hasLongitude()) {

					return false;
				}
				if (!hasLatitude()) {

					return false;
				}
				if (!hasAccuracy()) {

					return false;
				}
				if (!hasProvider()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						sampleTime_ = input.readInt64();
						break;
					}
					case 17: {
						bitField0_ |= 0x00000002;
						longitude_ = input.readDouble();
						break;
					}
					case 25: {
						bitField0_ |= 0x00000004;
						latitude_ = input.readDouble();
						break;
					}
					case 33: {
						bitField0_ |= 0x00000008;
						accuracy_ = input.readDouble();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						provider_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int64 sampleTime = 1;
			private long sampleTime_;

			public boolean hasSampleTime() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public long getSampleTime() {
				return sampleTime_;
			}

			public Builder setSampleTime(long value) {
				bitField0_ |= 0x00000001;
				sampleTime_ = value;
				onChanged();
				return this;
			}

			public Builder clearSampleTime() {
				bitField0_ = (bitField0_ & ~0x00000001);
				sampleTime_ = 0L;
				onChanged();
				return this;
			}

			// required double longitude = 2;
			private double longitude_;

			public boolean hasLongitude() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public double getLongitude() {
				return longitude_;
			}

			public Builder setLongitude(double value) {
				bitField0_ |= 0x00000002;
				longitude_ = value;
				onChanged();
				return this;
			}

			public Builder clearLongitude() {
				bitField0_ = (bitField0_ & ~0x00000002);
				longitude_ = 0D;
				onChanged();
				return this;
			}

			// required double latitude = 3;
			private double latitude_;

			public boolean hasLatitude() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public double getLatitude() {
				return latitude_;
			}

			public Builder setLatitude(double value) {
				bitField0_ |= 0x00000004;
				latitude_ = value;
				onChanged();
				return this;
			}

			public Builder clearLatitude() {
				bitField0_ = (bitField0_ & ~0x00000004);
				latitude_ = 0D;
				onChanged();
				return this;
			}

			// required double accuracy = 4;
			private double accuracy_;

			public boolean hasAccuracy() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public double getAccuracy() {
				return accuracy_;
			}

			public Builder setAccuracy(double value) {
				bitField0_ |= 0x00000008;
				accuracy_ = value;
				onChanged();
				return this;
			}

			public Builder clearAccuracy() {
				bitField0_ = (bitField0_ & ~0x00000008);
				accuracy_ = 0D;
				onChanged();
				return this;
			}

			// required string provider = 5;
			private java.lang.Object provider_ = "";

			public boolean hasProvider() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public String getProvider() {
				java.lang.Object ref = provider_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					provider_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setProvider(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				provider_ = value;
				onChanged();
				return this;
			}

			public Builder clearProvider() {
				bitField0_ = (bitField0_ & ~0x00000010);
				provider_ = getDefaultInstance().getProvider();
				onChanged();
				return this;
			}

			void setProvider(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				provider_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:proto.DataLocationProto)
		}

		static {
			defaultInstance = new DataLocationProto(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataLocationProto)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataLocationProtoList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataLocationProtoList_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataLocationProto_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataLocationProto_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\030DataLocationProtos.proto\022\005proto\"?\n\025Dat"
				+ "aLocationProtoList\022&\n\004list\030\001 \003(\0132\030.proto"
				+ ".DataLocationProto\"p\n\021DataLocationProto\022"
				+ "\022\n\nsampleTime\030\001 \002(\003\022\021\n\tlongitude\030\002 \002(\001\022\020"
				+ "\n\010latitude\030\003 \002(\001\022\020\n\010accuracy\030\004 \002(\001\022\020\n\010pr"
				+ "ovider\030\005 \002(\tB7\n!it.unibo.participact.dom"
				+ "ain.protoB\022DataLocationProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_proto_DataLocationProtoList_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_proto_DataLocationProtoList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataLocationProtoList_descriptor,
						new java.lang.String[] { "List", },
						it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList.class,
						it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProtoList.Builder.class);
				internal_static_proto_DataLocationProto_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_proto_DataLocationProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataLocationProto_descriptor,
						new java.lang.String[] { "SampleTime", "Longitude",
								"Latitude", "Accuracy", "Provider", },
						it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.class,
						it.unibo.participact.domain.proto.DataLocationProtos.DataLocationProto.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
