/*******************************************************************************
 * Participact
 * Copyright 2013-2018 Alma Mater Studiorum - Università di Bologna
 * 
 * This file is part of ParticipAct.
 * 
 * ParticipAct is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 * 
 * ParticipAct is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with ParticipAct. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBatteryProtos.proto

package it.unibo.participact.domain.proto;

public final class DataBatteryProtos {
	private DataBatteryProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface DataBatteryProtoListOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .proto.DataBatteryProto list = 1;
		java.util.List<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto> getListList();

		it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto getList(
				int index);

		int getListCount();

		java.util.List<? extends it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder> getListOrBuilderList();

		it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder getListOrBuilder(
				int index);
	}

	public static final class DataBatteryProtoList extends
			com.google.protobuf.GeneratedMessage implements
			DataBatteryProtoListOrBuilder {
		// Use DataBatteryProtoList.newBuilder() to construct.
		private DataBatteryProtoList(Builder builder) {
			super(builder);
		}

		private DataBatteryProtoList(boolean noInit) {
		}

		private static final DataBatteryProtoList defaultInstance;

		public static DataBatteryProtoList getDefaultInstance() {
			return defaultInstance;
		}

		public DataBatteryProtoList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProtoList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProtoList_fieldAccessorTable;
		}

		// repeated .proto.DataBatteryProto list = 1;
		public static final int LIST_FIELD_NUMBER = 1;
		private java.util.List<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto> list_;

		public java.util.List<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto> getListList() {
			return list_;
		}

		public java.util.List<? extends it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder> getListOrBuilderList() {
			return list_;
		}

		public int getListCount() {
			return list_.size();
		}

		public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto getList(
				int index) {
			return list_.get(index);
		}

		public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder getListOrBuilder(
				int index) {
			return list_.get(index);
		}

		private void initFields() {
			list_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getListCount(); i++) {
				if (!getList(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < list_.size(); i++) {
				output.writeMessage(1, list_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < list_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, list_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProtoList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProtoList_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getListFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList build() {
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList buildPartial() {
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList result = new it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList(
						this);
				int from_bitField0_ = bitField0_;
				if (listBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						list_ = java.util.Collections.unmodifiableList(list_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.list_ = list_;
				} else {
					result.list_ = listBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList) {
					return mergeFrom((it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList other) {
				if (other == it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList
						.getDefaultInstance())
					return this;
				if (listBuilder_ == null) {
					if (!other.list_.isEmpty()) {
						if (list_.isEmpty()) {
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureListIsMutable();
							list_.addAll(other.list_);
						}
						onChanged();
					}
				} else {
					if (!other.list_.isEmpty()) {
						if (listBuilder_.isEmpty()) {
							listBuilder_.dispose();
							listBuilder_ = null;
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
							listBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getListFieldBuilder()
									: null;
						} else {
							listBuilder_.addAllMessages(other.list_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getListCount(); i++) {
					if (!getList(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder subBuilder = it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addList(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .proto.DataBatteryProto list = 1;
			private java.util.List<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto> list_ = java.util.Collections
					.emptyList();

			private void ensureListIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto>(
							list_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto, it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder, it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder> listBuilder_;

			public java.util.List<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto> getListList() {
				if (listBuilder_ == null) {
					return java.util.Collections.unmodifiableList(list_);
				} else {
					return listBuilder_.getMessageList();
				}
			}

			public int getListCount() {
				if (listBuilder_ == null) {
					return list_.size();
				} else {
					return listBuilder_.getCount();
				}
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto getList(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessage(index);
				}
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.set(index, value);
					onChanged();
				} else {
					listBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.set(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(value);
					onChanged();
				} else {
					listBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(index, value);
					onChanged();
				} else {
					listBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllList(
					java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto> values) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					super.addAll(values, list_);
					onChanged();
				} else {
					listBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearList() {
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder removeList(int index) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.remove(index);
					onChanged();
				} else {
					listBuilder_.remove(index);
				}
				return this;
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder getListBuilder(
					int index) {
				return getListFieldBuilder().getBuilder(index);
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder getListOrBuilder(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder> getListOrBuilderList() {
				if (listBuilder_ != null) {
					return listBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(list_);
				}
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder addListBuilder() {
				return getListFieldBuilder()
						.addBuilder(
								it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto
										.getDefaultInstance());
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder addListBuilder(
					int index) {
				return getListFieldBuilder()
						.addBuilder(
								index,
								it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto
										.getDefaultInstance());
			}

			public java.util.List<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder> getListBuilderList() {
				return getListFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto, it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder, it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder> getListFieldBuilder() {
				if (listBuilder_ == null) {
					listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto, it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder, it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder>(
							list_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					list_ = null;
				}
				return listBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataBatteryProtoList)
		}

		static {
			defaultInstance = new DataBatteryProtoList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataBatteryProtoList)
	}

	public interface DataBatteryProtoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int64 sampleTime = 1;
		boolean hasSampleTime();

		long getSampleTime();

		// required int32 level = 2;
		boolean hasLevel();

		int getLevel();

		// required int32 scale = 3;
		boolean hasScale();

		int getScale();

		// required int32 temperature = 4;
		boolean hasTemperature();

		int getTemperature();

		// required int32 voltage = 5;
		boolean hasVoltage();

		int getVoltage();

		// required int32 plugged = 6;
		boolean hasPlugged();

		int getPlugged();

		// required int32 status = 7;
		boolean hasStatus();

		int getStatus();

		// required int32 health = 8;
		boolean hasHealth();

		int getHealth();
	}

	public static final class DataBatteryProto extends
			com.google.protobuf.GeneratedMessage implements
			DataBatteryProtoOrBuilder {
		// Use DataBatteryProto.newBuilder() to construct.
		private DataBatteryProto(Builder builder) {
			super(builder);
		}

		private DataBatteryProto(boolean noInit) {
		}

		private static final DataBatteryProto defaultInstance;

		public static DataBatteryProto getDefaultInstance() {
			return defaultInstance;
		}

		public DataBatteryProto getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProto_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProto_fieldAccessorTable;
		}

		private int bitField0_;
		// required int64 sampleTime = 1;
		public static final int SAMPLETIME_FIELD_NUMBER = 1;
		private long sampleTime_;

		public boolean hasSampleTime() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public long getSampleTime() {
			return sampleTime_;
		}

		// required int32 level = 2;
		public static final int LEVEL_FIELD_NUMBER = 2;
		private int level_;

		public boolean hasLevel() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public int getLevel() {
			return level_;
		}

		// required int32 scale = 3;
		public static final int SCALE_FIELD_NUMBER = 3;
		private int scale_;

		public boolean hasScale() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public int getScale() {
			return scale_;
		}

		// required int32 temperature = 4;
		public static final int TEMPERATURE_FIELD_NUMBER = 4;
		private int temperature_;

		public boolean hasTemperature() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public int getTemperature() {
			return temperature_;
		}

		// required int32 voltage = 5;
		public static final int VOLTAGE_FIELD_NUMBER = 5;
		private int voltage_;

		public boolean hasVoltage() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public int getVoltage() {
			return voltage_;
		}

		// required int32 plugged = 6;
		public static final int PLUGGED_FIELD_NUMBER = 6;
		private int plugged_;

		public boolean hasPlugged() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		public int getPlugged() {
			return plugged_;
		}

		// required int32 status = 7;
		public static final int STATUS_FIELD_NUMBER = 7;
		private int status_;

		public boolean hasStatus() {
			return ((bitField0_ & 0x00000040) == 0x00000040);
		}

		public int getStatus() {
			return status_;
		}

		// required int32 health = 8;
		public static final int HEALTH_FIELD_NUMBER = 8;
		private int health_;

		public boolean hasHealth() {
			return ((bitField0_ & 0x00000080) == 0x00000080);
		}

		public int getHealth() {
			return health_;
		}

		private void initFields() {
			sampleTime_ = 0L;
			level_ = 0;
			scale_ = 0;
			temperature_ = 0;
			voltage_ = 0;
			plugged_ = 0;
			status_ = 0;
			health_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasSampleTime()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasLevel()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasScale()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasTemperature()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasVoltage()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasPlugged()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasStatus()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasHealth()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, level_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, scale_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeInt32(4, temperature_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeInt32(5, voltage_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeInt32(6, plugged_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				output.writeInt32(7, status_);
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				output.writeInt32(8, health_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, level_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, scale_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						4, temperature_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						5, voltage_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						6, plugged_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						7, status_);
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						8, health_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProto_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.internal_static_proto_DataBatteryProto_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				sampleTime_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				level_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				scale_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				temperature_ = 0;
				bitField0_ = (bitField0_ & ~0x00000008);
				voltage_ = 0;
				bitField0_ = (bitField0_ & ~0x00000010);
				plugged_ = 0;
				bitField0_ = (bitField0_ & ~0x00000020);
				status_ = 0;
				bitField0_ = (bitField0_ & ~0x00000040);
				health_ = 0;
				bitField0_ = (bitField0_ & ~0x00000080);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto build() {
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto buildPartial() {
				it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto result = new it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.sampleTime_ = sampleTime_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.level_ = level_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.scale_ = scale_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.temperature_ = temperature_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.voltage_ = voltage_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000020;
				}
				result.plugged_ = plugged_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000040;
				}
				result.status_ = status_;
				if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
					to_bitField0_ |= 0x00000080;
				}
				result.health_ = health_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto) {
					return mergeFrom((it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto other) {
				if (other == it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto
						.getDefaultInstance())
					return this;
				if (other.hasSampleTime()) {
					setSampleTime(other.getSampleTime());
				}
				if (other.hasLevel()) {
					setLevel(other.getLevel());
				}
				if (other.hasScale()) {
					setScale(other.getScale());
				}
				if (other.hasTemperature()) {
					setTemperature(other.getTemperature());
				}
				if (other.hasVoltage()) {
					setVoltage(other.getVoltage());
				}
				if (other.hasPlugged()) {
					setPlugged(other.getPlugged());
				}
				if (other.hasStatus()) {
					setStatus(other.getStatus());
				}
				if (other.hasHealth()) {
					setHealth(other.getHealth());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasSampleTime()) {

					return false;
				}
				if (!hasLevel()) {

					return false;
				}
				if (!hasScale()) {

					return false;
				}
				if (!hasTemperature()) {

					return false;
				}
				if (!hasVoltage()) {

					return false;
				}
				if (!hasPlugged()) {

					return false;
				}
				if (!hasStatus()) {

					return false;
				}
				if (!hasHealth()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						sampleTime_ = input.readInt64();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						level_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						scale_ = input.readInt32();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						temperature_ = input.readInt32();
						break;
					}
					case 40: {
						bitField0_ |= 0x00000010;
						voltage_ = input.readInt32();
						break;
					}
					case 48: {
						bitField0_ |= 0x00000020;
						plugged_ = input.readInt32();
						break;
					}
					case 56: {
						bitField0_ |= 0x00000040;
						status_ = input.readInt32();
						break;
					}
					case 64: {
						bitField0_ |= 0x00000080;
						health_ = input.readInt32();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int64 sampleTime = 1;
			private long sampleTime_;

			public boolean hasSampleTime() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public long getSampleTime() {
				return sampleTime_;
			}

			public Builder setSampleTime(long value) {
				bitField0_ |= 0x00000001;
				sampleTime_ = value;
				onChanged();
				return this;
			}

			public Builder clearSampleTime() {
				bitField0_ = (bitField0_ & ~0x00000001);
				sampleTime_ = 0L;
				onChanged();
				return this;
			}

			// required int32 level = 2;
			private int level_;

			public boolean hasLevel() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public int getLevel() {
				return level_;
			}

			public Builder setLevel(int value) {
				bitField0_ |= 0x00000002;
				level_ = value;
				onChanged();
				return this;
			}

			public Builder clearLevel() {
				bitField0_ = (bitField0_ & ~0x00000002);
				level_ = 0;
				onChanged();
				return this;
			}

			// required int32 scale = 3;
			private int scale_;

			public boolean hasScale() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public int getScale() {
				return scale_;
			}

			public Builder setScale(int value) {
				bitField0_ |= 0x00000004;
				scale_ = value;
				onChanged();
				return this;
			}

			public Builder clearScale() {
				bitField0_ = (bitField0_ & ~0x00000004);
				scale_ = 0;
				onChanged();
				return this;
			}

			// required int32 temperature = 4;
			private int temperature_;

			public boolean hasTemperature() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public int getTemperature() {
				return temperature_;
			}

			public Builder setTemperature(int value) {
				bitField0_ |= 0x00000008;
				temperature_ = value;
				onChanged();
				return this;
			}

			public Builder clearTemperature() {
				bitField0_ = (bitField0_ & ~0x00000008);
				temperature_ = 0;
				onChanged();
				return this;
			}

			// required int32 voltage = 5;
			private int voltage_;

			public boolean hasVoltage() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public int getVoltage() {
				return voltage_;
			}

			public Builder setVoltage(int value) {
				bitField0_ |= 0x00000010;
				voltage_ = value;
				onChanged();
				return this;
			}

			public Builder clearVoltage() {
				bitField0_ = (bitField0_ & ~0x00000010);
				voltage_ = 0;
				onChanged();
				return this;
			}

			// required int32 plugged = 6;
			private int plugged_;

			public boolean hasPlugged() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			public int getPlugged() {
				return plugged_;
			}

			public Builder setPlugged(int value) {
				bitField0_ |= 0x00000020;
				plugged_ = value;
				onChanged();
				return this;
			}

			public Builder clearPlugged() {
				bitField0_ = (bitField0_ & ~0x00000020);
				plugged_ = 0;
				onChanged();
				return this;
			}

			// required int32 status = 7;
			private int status_;

			public boolean hasStatus() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			public int getStatus() {
				return status_;
			}

			public Builder setStatus(int value) {
				bitField0_ |= 0x00000040;
				status_ = value;
				onChanged();
				return this;
			}

			public Builder clearStatus() {
				bitField0_ = (bitField0_ & ~0x00000040);
				status_ = 0;
				onChanged();
				return this;
			}

			// required int32 health = 8;
			private int health_;

			public boolean hasHealth() {
				return ((bitField0_ & 0x00000080) == 0x00000080);
			}

			public int getHealth() {
				return health_;
			}

			public Builder setHealth(int value) {
				bitField0_ |= 0x00000080;
				health_ = value;
				onChanged();
				return this;
			}

			public Builder clearHealth() {
				bitField0_ = (bitField0_ & ~0x00000080);
				health_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataBatteryProto)
		}

		static {
			defaultInstance = new DataBatteryProto(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataBatteryProto)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataBatteryProtoList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataBatteryProtoList_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataBatteryProto_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataBatteryProto_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\027DataBatteryProtos.proto\022\005proto\"=\n\024Data"
				+ "BatteryProtoList\022%\n\004list\030\001 \003(\0132\027.proto.D"
				+ "ataBatteryProto\"\233\001\n\020DataBatteryProto\022\022\n\n"
				+ "sampleTime\030\001 \002(\003\022\r\n\005level\030\002 \002(\005\022\r\n\005scale"
				+ "\030\003 \002(\005\022\023\n\013temperature\030\004 \002(\005\022\017\n\007voltage\030\005"
				+ " \002(\005\022\017\n\007plugged\030\006 \002(\005\022\016\n\006status\030\007 \002(\005\022\016\n"
				+ "\006health\030\010 \002(\005B6\n!it.unibo.participact.do"
				+ "main.protoB\021DataBatteryProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_proto_DataBatteryProtoList_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_proto_DataBatteryProtoList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataBatteryProtoList_descriptor,
						new java.lang.String[] { "List", },
						it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList.class,
						it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProtoList.Builder.class);
				internal_static_proto_DataBatteryProto_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_proto_DataBatteryProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataBatteryProto_descriptor,
						new java.lang.String[] { "SampleTime", "Level",
								"Scale", "Temperature", "Voltage", "Plugged",
								"Status", "Health", },
						it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.class,
						it.unibo.participact.domain.proto.DataBatteryProtos.DataBatteryProto.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
