/*******************************************************************************
 * Participact
 * Copyright 2013-2018 Alma Mater Studiorum - Università di Bologna
 * 
 * This file is part of ParticipAct.
 * 
 * ParticipAct is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 * 
 * ParticipAct is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with ParticipAct. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBluetoothProtos.proto

package it.unibo.participact.domain.proto;

public final class DataBluetoothProtos {
	private DataBluetoothProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface DataBluetoothProtoListOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .proto.DataBluetoothProto list = 1;
		java.util.List<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto> getListList();

		it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto getList(
				int index);

		int getListCount();

		java.util.List<? extends it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder> getListOrBuilderList();

		it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder getListOrBuilder(
				int index);
	}

	public static final class DataBluetoothProtoList extends
			com.google.protobuf.GeneratedMessage implements
			DataBluetoothProtoListOrBuilder {
		// Use DataBluetoothProtoList.newBuilder() to construct.
		private DataBluetoothProtoList(Builder builder) {
			super(builder);
		}

		private DataBluetoothProtoList(boolean noInit) {
		}

		private static final DataBluetoothProtoList defaultInstance;

		public static DataBluetoothProtoList getDefaultInstance() {
			return defaultInstance;
		}

		public DataBluetoothProtoList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProtoList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProtoList_fieldAccessorTable;
		}

		// repeated .proto.DataBluetoothProto list = 1;
		public static final int LIST_FIELD_NUMBER = 1;
		private java.util.List<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto> list_;

		public java.util.List<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto> getListList() {
			return list_;
		}

		public java.util.List<? extends it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder> getListOrBuilderList() {
			return list_;
		}

		public int getListCount() {
			return list_.size();
		}

		public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto getList(
				int index) {
			return list_.get(index);
		}

		public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder getListOrBuilder(
				int index) {
			return list_.get(index);
		}

		private void initFields() {
			list_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getListCount(); i++) {
				if (!getList(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < list_.size(); i++) {
				output.writeMessage(1, list_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < list_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, list_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProtoList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProtoList_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getListFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList build() {
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList buildPartial() {
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList result = new it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList(
						this);
				int from_bitField0_ = bitField0_;
				if (listBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						list_ = java.util.Collections.unmodifiableList(list_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.list_ = list_;
				} else {
					result.list_ = listBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList) {
					return mergeFrom((it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList other) {
				if (other == it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList
						.getDefaultInstance())
					return this;
				if (listBuilder_ == null) {
					if (!other.list_.isEmpty()) {
						if (list_.isEmpty()) {
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureListIsMutable();
							list_.addAll(other.list_);
						}
						onChanged();
					}
				} else {
					if (!other.list_.isEmpty()) {
						if (listBuilder_.isEmpty()) {
							listBuilder_.dispose();
							listBuilder_ = null;
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
							listBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getListFieldBuilder()
									: null;
						} else {
							listBuilder_.addAllMessages(other.list_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getListCount(); i++) {
					if (!getList(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder subBuilder = it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addList(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .proto.DataBluetoothProto list = 1;
			private java.util.List<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto> list_ = java.util.Collections
					.emptyList();

			private void ensureListIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto>(
							list_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto, it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder, it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder> listBuilder_;

			public java.util.List<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto> getListList() {
				if (listBuilder_ == null) {
					return java.util.Collections.unmodifiableList(list_);
				} else {
					return listBuilder_.getMessageList();
				}
			}

			public int getListCount() {
				if (listBuilder_ == null) {
					return list_.size();
				} else {
					return listBuilder_.getCount();
				}
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto getList(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessage(index);
				}
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.set(index, value);
					onChanged();
				} else {
					listBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.set(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(value);
					onChanged();
				} else {
					listBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(index, value);
					onChanged();
				} else {
					listBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllList(
					java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto> values) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					super.addAll(values, list_);
					onChanged();
				} else {
					listBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearList() {
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder removeList(int index) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.remove(index);
					onChanged();
				} else {
					listBuilder_.remove(index);
				}
				return this;
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder getListBuilder(
					int index) {
				return getListFieldBuilder().getBuilder(index);
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder getListOrBuilder(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder> getListOrBuilderList() {
				if (listBuilder_ != null) {
					return listBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(list_);
				}
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder addListBuilder() {
				return getListFieldBuilder()
						.addBuilder(
								it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto
										.getDefaultInstance());
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder addListBuilder(
					int index) {
				return getListFieldBuilder()
						.addBuilder(
								index,
								it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto
										.getDefaultInstance());
			}

			public java.util.List<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder> getListBuilderList() {
				return getListFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto, it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder, it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder> getListFieldBuilder() {
				if (listBuilder_ == null) {
					listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto, it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder, it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder>(
							list_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					list_ = null;
				}
				return listBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataBluetoothProtoList)
		}

		static {
			defaultInstance = new DataBluetoothProtoList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataBluetoothProtoList)
	}

	public interface DataBluetoothProtoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int64 sampleTime = 1;
		boolean hasSampleTime();

		long getSampleTime();

		// required string mac = 2;
		boolean hasMac();

		String getMac();

		// required string friendly_name = 3;
		boolean hasFriendlyName();

		String getFriendlyName();

		// required int32 deviceClass = 4;
		boolean hasDeviceClass();

		int getDeviceClass();

		// required int32 major_class = 5;
		boolean hasMajorClass();

		int getMajorClass();
	}

	public static final class DataBluetoothProto extends
			com.google.protobuf.GeneratedMessage implements
			DataBluetoothProtoOrBuilder {
		// Use DataBluetoothProto.newBuilder() to construct.
		private DataBluetoothProto(Builder builder) {
			super(builder);
		}

		private DataBluetoothProto(boolean noInit) {
		}

		private static final DataBluetoothProto defaultInstance;

		public static DataBluetoothProto getDefaultInstance() {
			return defaultInstance;
		}

		public DataBluetoothProto getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProto_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProto_fieldAccessorTable;
		}

		private int bitField0_;
		// required int64 sampleTime = 1;
		public static final int SAMPLETIME_FIELD_NUMBER = 1;
		private long sampleTime_;

		public boolean hasSampleTime() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public long getSampleTime() {
			return sampleTime_;
		}

		// required string mac = 2;
		public static final int MAC_FIELD_NUMBER = 2;
		private java.lang.Object mac_;

		public boolean hasMac() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getMac() {
			java.lang.Object ref = mac_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					mac_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getMacBytes() {
			java.lang.Object ref = mac_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				mac_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string friendly_name = 3;
		public static final int FRIENDLY_NAME_FIELD_NUMBER = 3;
		private java.lang.Object friendlyName_;

		public boolean hasFriendlyName() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public String getFriendlyName() {
			java.lang.Object ref = friendlyName_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					friendlyName_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getFriendlyNameBytes() {
			java.lang.Object ref = friendlyName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				friendlyName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required int32 deviceClass = 4;
		public static final int DEVICECLASS_FIELD_NUMBER = 4;
		private int deviceClass_;

		public boolean hasDeviceClass() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public int getDeviceClass() {
			return deviceClass_;
		}

		// required int32 major_class = 5;
		public static final int MAJOR_CLASS_FIELD_NUMBER = 5;
		private int majorClass_;

		public boolean hasMajorClass() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public int getMajorClass() {
			return majorClass_;
		}

		private void initFields() {
			sampleTime_ = 0L;
			mac_ = "";
			friendlyName_ = "";
			deviceClass_ = 0;
			majorClass_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasSampleTime()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMac()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasFriendlyName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasDeviceClass()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMajorClass()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getMacBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getFriendlyNameBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeInt32(4, deviceClass_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeInt32(5, majorClass_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getMacBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						3, getFriendlyNameBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						4, deviceClass_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						5, majorClass_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProto_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.internal_static_proto_DataBluetoothProto_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				sampleTime_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				mac_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				friendlyName_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				deviceClass_ = 0;
				bitField0_ = (bitField0_ & ~0x00000008);
				majorClass_ = 0;
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto build() {
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto buildPartial() {
				it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto result = new it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.sampleTime_ = sampleTime_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.mac_ = mac_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.friendlyName_ = friendlyName_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.deviceClass_ = deviceClass_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.majorClass_ = majorClass_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto) {
					return mergeFrom((it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto other) {
				if (other == it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto
						.getDefaultInstance())
					return this;
				if (other.hasSampleTime()) {
					setSampleTime(other.getSampleTime());
				}
				if (other.hasMac()) {
					setMac(other.getMac());
				}
				if (other.hasFriendlyName()) {
					setFriendlyName(other.getFriendlyName());
				}
				if (other.hasDeviceClass()) {
					setDeviceClass(other.getDeviceClass());
				}
				if (other.hasMajorClass()) {
					setMajorClass(other.getMajorClass());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasSampleTime()) {

					return false;
				}
				if (!hasMac()) {

					return false;
				}
				if (!hasFriendlyName()) {

					return false;
				}
				if (!hasDeviceClass()) {

					return false;
				}
				if (!hasMajorClass()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						sampleTime_ = input.readInt64();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						mac_ = input.readBytes();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						friendlyName_ = input.readBytes();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						deviceClass_ = input.readInt32();
						break;
					}
					case 40: {
						bitField0_ |= 0x00000010;
						majorClass_ = input.readInt32();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int64 sampleTime = 1;
			private long sampleTime_;

			public boolean hasSampleTime() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public long getSampleTime() {
				return sampleTime_;
			}

			public Builder setSampleTime(long value) {
				bitField0_ |= 0x00000001;
				sampleTime_ = value;
				onChanged();
				return this;
			}

			public Builder clearSampleTime() {
				bitField0_ = (bitField0_ & ~0x00000001);
				sampleTime_ = 0L;
				onChanged();
				return this;
			}

			// required string mac = 2;
			private java.lang.Object mac_ = "";

			public boolean hasMac() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getMac() {
				java.lang.Object ref = mac_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					mac_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setMac(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				mac_ = value;
				onChanged();
				return this;
			}

			public Builder clearMac() {
				bitField0_ = (bitField0_ & ~0x00000002);
				mac_ = getDefaultInstance().getMac();
				onChanged();
				return this;
			}

			void setMac(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				mac_ = value;
				onChanged();
			}

			// required string friendly_name = 3;
			private java.lang.Object friendlyName_ = "";

			public boolean hasFriendlyName() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public String getFriendlyName() {
				java.lang.Object ref = friendlyName_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					friendlyName_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setFriendlyName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				friendlyName_ = value;
				onChanged();
				return this;
			}

			public Builder clearFriendlyName() {
				bitField0_ = (bitField0_ & ~0x00000004);
				friendlyName_ = getDefaultInstance().getFriendlyName();
				onChanged();
				return this;
			}

			void setFriendlyName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000004;
				friendlyName_ = value;
				onChanged();
			}

			// required int32 deviceClass = 4;
			private int deviceClass_;

			public boolean hasDeviceClass() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public int getDeviceClass() {
				return deviceClass_;
			}

			public Builder setDeviceClass(int value) {
				bitField0_ |= 0x00000008;
				deviceClass_ = value;
				onChanged();
				return this;
			}

			public Builder clearDeviceClass() {
				bitField0_ = (bitField0_ & ~0x00000008);
				deviceClass_ = 0;
				onChanged();
				return this;
			}

			// required int32 major_class = 5;
			private int majorClass_;

			public boolean hasMajorClass() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public int getMajorClass() {
				return majorClass_;
			}

			public Builder setMajorClass(int value) {
				bitField0_ |= 0x00000010;
				majorClass_ = value;
				onChanged();
				return this;
			}

			public Builder clearMajorClass() {
				bitField0_ = (bitField0_ & ~0x00000010);
				majorClass_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataBluetoothProto)
		}

		static {
			defaultInstance = new DataBluetoothProto(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataBluetoothProto)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataBluetoothProtoList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataBluetoothProtoList_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataBluetoothProto_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataBluetoothProto_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\031DataBluetoothProtos.proto\022\005proto\"A\n\026Da"
				+ "taBluetoothProtoList\022\'\n\004list\030\001 \003(\0132\031.pro"
				+ "to.DataBluetoothProto\"v\n\022DataBluetoothPr"
				+ "oto\022\022\n\nsampleTime\030\001 \002(\003\022\013\n\003mac\030\002 \002(\t\022\025\n\r"
				+ "friendly_name\030\003 \002(\t\022\023\n\013deviceClass\030\004 \002(\005"
				+ "\022\023\n\013major_class\030\005 \002(\005B8\n!it.unibo.partic"
				+ "ipact.domain.protoB\023DataBluetoothProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_proto_DataBluetoothProtoList_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_proto_DataBluetoothProtoList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataBluetoothProtoList_descriptor,
						new java.lang.String[] { "List", },
						it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList.class,
						it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProtoList.Builder.class);
				internal_static_proto_DataBluetoothProto_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_proto_DataBluetoothProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataBluetoothProto_descriptor,
						new java.lang.String[] { "SampleTime", "Mac",
								"FriendlyName", "DeviceClass", "MajorClass", },
						it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.class,
						it.unibo.participact.domain.proto.DataBluetoothProtos.DataBluetoothProto.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
