/*******************************************************************************
 * Participact
 * Copyright 2013-2018 Alma Mater Studiorum - Università di Bologna
 * 
 * This file is part of ParticipAct.
 * 
 * ParticipAct is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 * 
 * ParticipAct is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with ParticipAct. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataMagneticFieldProtos.proto

package it.unibo.participact.domain.proto;

public final class DataMagneticFieldProtos {
	private DataMagneticFieldProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface DataMagneticFieldProtoListOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .proto.DataMagneticFieldProto list = 1;
		java.util.List<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto> getListList();

		it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto getList(
				int index);

		int getListCount();

		java.util.List<? extends it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder> getListOrBuilderList();

		it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder getListOrBuilder(
				int index);
	}

	public static final class DataMagneticFieldProtoList extends
			com.google.protobuf.GeneratedMessage implements
			DataMagneticFieldProtoListOrBuilder {
		// Use DataMagneticFieldProtoList.newBuilder() to construct.
		private DataMagneticFieldProtoList(Builder builder) {
			super(builder);
		}

		private DataMagneticFieldProtoList(boolean noInit) {
		}

		private static final DataMagneticFieldProtoList defaultInstance;

		public static DataMagneticFieldProtoList getDefaultInstance() {
			return defaultInstance;
		}

		public DataMagneticFieldProtoList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProtoList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProtoList_fieldAccessorTable;
		}

		// repeated .proto.DataMagneticFieldProto list = 1;
		public static final int LIST_FIELD_NUMBER = 1;
		private java.util.List<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto> list_;

		public java.util.List<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto> getListList() {
			return list_;
		}

		public java.util.List<? extends it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder> getListOrBuilderList() {
			return list_;
		}

		public int getListCount() {
			return list_.size();
		}

		public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto getList(
				int index) {
			return list_.get(index);
		}

		public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder getListOrBuilder(
				int index) {
			return list_.get(index);
		}

		private void initFields() {
			list_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getListCount(); i++) {
				if (!getList(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < list_.size(); i++) {
				output.writeMessage(1, list_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < list_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, list_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProtoList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProtoList_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getListFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList build() {
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList buildPartial() {
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList result = new it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList(
						this);
				int from_bitField0_ = bitField0_;
				if (listBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						list_ = java.util.Collections.unmodifiableList(list_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.list_ = list_;
				} else {
					result.list_ = listBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList) {
					return mergeFrom((it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList other) {
				if (other == it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList
						.getDefaultInstance())
					return this;
				if (listBuilder_ == null) {
					if (!other.list_.isEmpty()) {
						if (list_.isEmpty()) {
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureListIsMutable();
							list_.addAll(other.list_);
						}
						onChanged();
					}
				} else {
					if (!other.list_.isEmpty()) {
						if (listBuilder_.isEmpty()) {
							listBuilder_.dispose();
							listBuilder_ = null;
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
							listBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getListFieldBuilder()
									: null;
						} else {
							listBuilder_.addAllMessages(other.list_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getListCount(); i++) {
					if (!getList(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder subBuilder = it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addList(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .proto.DataMagneticFieldProto list = 1;
			private java.util.List<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto> list_ = java.util.Collections
					.emptyList();

			private void ensureListIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto>(
							list_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto, it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder, it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder> listBuilder_;

			public java.util.List<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto> getListList() {
				if (listBuilder_ == null) {
					return java.util.Collections.unmodifiableList(list_);
				} else {
					return listBuilder_.getMessageList();
				}
			}

			public int getListCount() {
				if (listBuilder_ == null) {
					return list_.size();
				} else {
					return listBuilder_.getCount();
				}
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto getList(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessage(index);
				}
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.set(index, value);
					onChanged();
				} else {
					listBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.set(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(value);
					onChanged();
				} else {
					listBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(index, value);
					onChanged();
				} else {
					listBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllList(
					java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto> values) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					super.addAll(values, list_);
					onChanged();
				} else {
					listBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearList() {
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder removeList(int index) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.remove(index);
					onChanged();
				} else {
					listBuilder_.remove(index);
				}
				return this;
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder getListBuilder(
					int index) {
				return getListFieldBuilder().getBuilder(index);
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder getListOrBuilder(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder> getListOrBuilderList() {
				if (listBuilder_ != null) {
					return listBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(list_);
				}
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder addListBuilder() {
				return getListFieldBuilder()
						.addBuilder(
								it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto
										.getDefaultInstance());
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder addListBuilder(
					int index) {
				return getListFieldBuilder()
						.addBuilder(
								index,
								it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto
										.getDefaultInstance());
			}

			public java.util.List<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder> getListBuilderList() {
				return getListFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto, it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder, it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder> getListFieldBuilder() {
				if (listBuilder_ == null) {
					listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto, it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder, it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder>(
							list_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					list_ = null;
				}
				return listBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataMagneticFieldProtoList)
		}

		static {
			defaultInstance = new DataMagneticFieldProtoList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataMagneticFieldProtoList)
	}

	public interface DataMagneticFieldProtoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int64 sampleTime = 1;
		boolean hasSampleTime();

		long getSampleTime();

		// required float magnetic_field_x = 2;
		boolean hasMagneticFieldX();

		float getMagneticFieldX();

		// required float magnetic_field_y = 3;
		boolean hasMagneticFieldY();

		float getMagneticFieldY();

		// required float magnetic_field_z = 4;
		boolean hasMagneticFieldZ();

		float getMagneticFieldZ();
	}

	public static final class DataMagneticFieldProto extends
			com.google.protobuf.GeneratedMessage implements
			DataMagneticFieldProtoOrBuilder {
		// Use DataMagneticFieldProto.newBuilder() to construct.
		private DataMagneticFieldProto(Builder builder) {
			super(builder);
		}

		private DataMagneticFieldProto(boolean noInit) {
		}

		private static final DataMagneticFieldProto defaultInstance;

		public static DataMagneticFieldProto getDefaultInstance() {
			return defaultInstance;
		}

		public DataMagneticFieldProto getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProto_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProto_fieldAccessorTable;
		}

		private int bitField0_;
		// required int64 sampleTime = 1;
		public static final int SAMPLETIME_FIELD_NUMBER = 1;
		private long sampleTime_;

		public boolean hasSampleTime() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public long getSampleTime() {
			return sampleTime_;
		}

		// required float magnetic_field_x = 2;
		public static final int MAGNETIC_FIELD_X_FIELD_NUMBER = 2;
		private float magneticFieldX_;

		public boolean hasMagneticFieldX() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public float getMagneticFieldX() {
			return magneticFieldX_;
		}

		// required float magnetic_field_y = 3;
		public static final int MAGNETIC_FIELD_Y_FIELD_NUMBER = 3;
		private float magneticFieldY_;

		public boolean hasMagneticFieldY() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public float getMagneticFieldY() {
			return magneticFieldY_;
		}

		// required float magnetic_field_z = 4;
		public static final int MAGNETIC_FIELD_Z_FIELD_NUMBER = 4;
		private float magneticFieldZ_;

		public boolean hasMagneticFieldZ() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public float getMagneticFieldZ() {
			return magneticFieldZ_;
		}

		private void initFields() {
			sampleTime_ = 0L;
			magneticFieldX_ = 0F;
			magneticFieldY_ = 0F;
			magneticFieldZ_ = 0F;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasSampleTime()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMagneticFieldX()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMagneticFieldY()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMagneticFieldZ()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeFloat(2, magneticFieldX_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeFloat(3, magneticFieldY_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeFloat(4, magneticFieldZ_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeFloatSize(
						2, magneticFieldX_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeFloatSize(
						3, magneticFieldY_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeFloatSize(
						4, magneticFieldZ_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProto_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.internal_static_proto_DataMagneticFieldProto_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				sampleTime_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				magneticFieldX_ = 0F;
				bitField0_ = (bitField0_ & ~0x00000002);
				magneticFieldY_ = 0F;
				bitField0_ = (bitField0_ & ~0x00000004);
				magneticFieldZ_ = 0F;
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto build() {
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto buildPartial() {
				it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto result = new it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.sampleTime_ = sampleTime_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.magneticFieldX_ = magneticFieldX_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.magneticFieldY_ = magneticFieldY_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.magneticFieldZ_ = magneticFieldZ_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto) {
					return mergeFrom((it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto other) {
				if (other == it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto
						.getDefaultInstance())
					return this;
				if (other.hasSampleTime()) {
					setSampleTime(other.getSampleTime());
				}
				if (other.hasMagneticFieldX()) {
					setMagneticFieldX(other.getMagneticFieldX());
				}
				if (other.hasMagneticFieldY()) {
					setMagneticFieldY(other.getMagneticFieldY());
				}
				if (other.hasMagneticFieldZ()) {
					setMagneticFieldZ(other.getMagneticFieldZ());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasSampleTime()) {

					return false;
				}
				if (!hasMagneticFieldX()) {

					return false;
				}
				if (!hasMagneticFieldY()) {

					return false;
				}
				if (!hasMagneticFieldZ()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						sampleTime_ = input.readInt64();
						break;
					}
					case 21: {
						bitField0_ |= 0x00000002;
						magneticFieldX_ = input.readFloat();
						break;
					}
					case 29: {
						bitField0_ |= 0x00000004;
						magneticFieldY_ = input.readFloat();
						break;
					}
					case 37: {
						bitField0_ |= 0x00000008;
						magneticFieldZ_ = input.readFloat();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int64 sampleTime = 1;
			private long sampleTime_;

			public boolean hasSampleTime() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public long getSampleTime() {
				return sampleTime_;
			}

			public Builder setSampleTime(long value) {
				bitField0_ |= 0x00000001;
				sampleTime_ = value;
				onChanged();
				return this;
			}

			public Builder clearSampleTime() {
				bitField0_ = (bitField0_ & ~0x00000001);
				sampleTime_ = 0L;
				onChanged();
				return this;
			}

			// required float magnetic_field_x = 2;
			private float magneticFieldX_;

			public boolean hasMagneticFieldX() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public float getMagneticFieldX() {
				return magneticFieldX_;
			}

			public Builder setMagneticFieldX(float value) {
				bitField0_ |= 0x00000002;
				magneticFieldX_ = value;
				onChanged();
				return this;
			}

			public Builder clearMagneticFieldX() {
				bitField0_ = (bitField0_ & ~0x00000002);
				magneticFieldX_ = 0F;
				onChanged();
				return this;
			}

			// required float magnetic_field_y = 3;
			private float magneticFieldY_;

			public boolean hasMagneticFieldY() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public float getMagneticFieldY() {
				return magneticFieldY_;
			}

			public Builder setMagneticFieldY(float value) {
				bitField0_ |= 0x00000004;
				magneticFieldY_ = value;
				onChanged();
				return this;
			}

			public Builder clearMagneticFieldY() {
				bitField0_ = (bitField0_ & ~0x00000004);
				magneticFieldY_ = 0F;
				onChanged();
				return this;
			}

			// required float magnetic_field_z = 4;
			private float magneticFieldZ_;

			public boolean hasMagneticFieldZ() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public float getMagneticFieldZ() {
				return magneticFieldZ_;
			}

			public Builder setMagneticFieldZ(float value) {
				bitField0_ |= 0x00000008;
				magneticFieldZ_ = value;
				onChanged();
				return this;
			}

			public Builder clearMagneticFieldZ() {
				bitField0_ = (bitField0_ & ~0x00000008);
				magneticFieldZ_ = 0F;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataMagneticFieldProto)
		}

		static {
			defaultInstance = new DataMagneticFieldProto(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataMagneticFieldProto)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataMagneticFieldProtoList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataMagneticFieldProtoList_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataMagneticFieldProto_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataMagneticFieldProto_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\035DataMagneticFieldProtos.proto\022\005proto\"I"
				+ "\n\032DataMagneticFieldProtoList\022+\n\004list\030\001 \003"
				+ "(\0132\035.proto.DataMagneticFieldProto\"z\n\026Dat"
				+ "aMagneticFieldProto\022\022\n\nsampleTime\030\001 \002(\003\022"
				+ "\030\n\020magnetic_field_x\030\002 \002(\002\022\030\n\020magnetic_fi"
				+ "eld_y\030\003 \002(\002\022\030\n\020magnetic_field_z\030\004 \002(\002B<\n"
				+ "!it.unibo.participact.domain.protoB\027Data"
				+ "MagneticFieldProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_proto_DataMagneticFieldProtoList_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_proto_DataMagneticFieldProtoList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataMagneticFieldProtoList_descriptor,
						new java.lang.String[] { "List", },
						it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList.class,
						it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProtoList.Builder.class);
				internal_static_proto_DataMagneticFieldProto_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_proto_DataMagneticFieldProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataMagneticFieldProto_descriptor,
						new java.lang.String[] { "SampleTime",
								"MagneticFieldX", "MagneticFieldY",
								"MagneticFieldZ", },
						it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.class,
						it.unibo.participact.domain.proto.DataMagneticFieldProtos.DataMagneticFieldProto.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
