/*******************************************************************************
 * Participact
 * Copyright 2013-2018 Alma Mater Studiorum - Università di Bologna
 * 
 * This file is part of ParticipAct.
 * 
 * ParticipAct is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 * 
 * ParticipAct is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with ParticipAct. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataQuestionnaireFlatProtos.proto

package it.unibo.participact.domain.proto;

public final class DataQuestionnaireFlatProtos {
	private DataQuestionnaireFlatProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface DataQuestionnaireFlatProtoListOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .proto.DataQuestionnaireFlatProto list = 1;
		java.util.List<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto> getListList();

		it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto getList(
				int index);

		int getListCount();

		java.util.List<? extends it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder> getListOrBuilderList();

		it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder getListOrBuilder(
				int index);
	}

	public static final class DataQuestionnaireFlatProtoList extends
			com.google.protobuf.GeneratedMessage implements
			DataQuestionnaireFlatProtoListOrBuilder {
		// Use DataQuestionnaireFlatProtoList.newBuilder() to construct.
		private DataQuestionnaireFlatProtoList(Builder builder) {
			super(builder);
		}

		private DataQuestionnaireFlatProtoList(boolean noInit) {
		}

		private static final DataQuestionnaireFlatProtoList defaultInstance;

		public static DataQuestionnaireFlatProtoList getDefaultInstance() {
			return defaultInstance;
		}

		public DataQuestionnaireFlatProtoList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProtoList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProtoList_fieldAccessorTable;
		}

		// repeated .proto.DataQuestionnaireFlatProto list = 1;
		public static final int LIST_FIELD_NUMBER = 1;
		private java.util.List<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto> list_;

		public java.util.List<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto> getListList() {
			return list_;
		}

		public java.util.List<? extends it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder> getListOrBuilderList() {
			return list_;
		}

		public int getListCount() {
			return list_.size();
		}

		public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto getList(
				int index) {
			return list_.get(index);
		}

		public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder getListOrBuilder(
				int index) {
			return list_.get(index);
		}

		private void initFields() {
			list_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getListCount(); i++) {
				if (!getList(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < list_.size(); i++) {
				output.writeMessage(1, list_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < list_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, list_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProtoList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProtoList_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getListFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList build() {
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList buildPartial() {
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList result = new it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList(
						this);
				int from_bitField0_ = bitField0_;
				if (listBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						list_ = java.util.Collections.unmodifiableList(list_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.list_ = list_;
				} else {
					result.list_ = listBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList) {
					return mergeFrom((it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList other) {
				if (other == it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList
						.getDefaultInstance())
					return this;
				if (listBuilder_ == null) {
					if (!other.list_.isEmpty()) {
						if (list_.isEmpty()) {
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureListIsMutable();
							list_.addAll(other.list_);
						}
						onChanged();
					}
				} else {
					if (!other.list_.isEmpty()) {
						if (listBuilder_.isEmpty()) {
							listBuilder_.dispose();
							listBuilder_ = null;
							list_ = other.list_;
							bitField0_ = (bitField0_ & ~0x00000001);
							listBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getListFieldBuilder()
									: null;
						} else {
							listBuilder_.addAllMessages(other.list_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getListCount(); i++) {
					if (!getList(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder subBuilder = it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addList(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .proto.DataQuestionnaireFlatProto list = 1;
			private java.util.List<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto> list_ = java.util.Collections
					.emptyList();

			private void ensureListIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					list_ = new java.util.ArrayList<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto>(
							list_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto, it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder, it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder> listBuilder_;

			public java.util.List<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto> getListList() {
				if (listBuilder_ == null) {
					return java.util.Collections.unmodifiableList(list_);
				} else {
					return listBuilder_.getMessageList();
				}
			}

			public int getListCount() {
				if (listBuilder_ == null) {
					return list_.size();
				} else {
					return listBuilder_.getCount();
				}
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto getList(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessage(index);
				}
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.set(index, value);
					onChanged();
				} else {
					listBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setList(
					int index,
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.set(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(value);
					onChanged();
				} else {
					listBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto value) {
				if (listBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureListIsMutable();
					list_.add(index, value);
					onChanged();
				} else {
					listBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addList(
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addList(
					int index,
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder builderForValue) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.add(index, builderForValue.build());
					onChanged();
				} else {
					listBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllList(
					java.lang.Iterable<? extends it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto> values) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					super.addAll(values, list_);
					onChanged();
				} else {
					listBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearList() {
				if (listBuilder_ == null) {
					list_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					listBuilder_.clear();
				}
				return this;
			}

			public Builder removeList(int index) {
				if (listBuilder_ == null) {
					ensureListIsMutable();
					list_.remove(index);
					onChanged();
				} else {
					listBuilder_.remove(index);
				}
				return this;
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder getListBuilder(
					int index) {
				return getListFieldBuilder().getBuilder(index);
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder getListOrBuilder(
					int index) {
				if (listBuilder_ == null) {
					return list_.get(index);
				} else {
					return listBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder> getListOrBuilderList() {
				if (listBuilder_ != null) {
					return listBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(list_);
				}
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder addListBuilder() {
				return getListFieldBuilder()
						.addBuilder(
								it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto
										.getDefaultInstance());
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder addListBuilder(
					int index) {
				return getListFieldBuilder()
						.addBuilder(
								index,
								it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto
										.getDefaultInstance());
			}

			public java.util.List<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder> getListBuilderList() {
				return getListFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto, it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder, it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder> getListFieldBuilder() {
				if (listBuilder_ == null) {
					listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto, it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder, it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder>(
							list_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					list_ = null;
				}
				return listBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:proto.DataQuestionnaireFlatProtoList)
		}

		static {
			defaultInstance = new DataQuestionnaireFlatProtoList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataQuestionnaireFlatProtoList)
	}

	public interface DataQuestionnaireFlatProtoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int64 sampleTime = 1;
		boolean hasSampleTime();

		long getSampleTime();

		// required int64 taskId = 2;
		boolean hasTaskId();

		long getTaskId();

		// required int64 actionId = 3;
		boolean hasActionId();

		long getActionId();

		// required int64 questionId = 4;
		boolean hasQuestionId();

		long getQuestionId();

		// required int32 type = 5;
		boolean hasType();

		int getType();

		// required int64 answerId = 6;
		boolean hasAnswerId();

		long getAnswerId();

		// required bool closedAnswerValue = 7;
		boolean hasClosedAnswerValue();

		boolean getClosedAnswerValue();

		// required string openAnswerValue = 8;
		boolean hasOpenAnswerValue();

		String getOpenAnswerValue();
	}

	public static final class DataQuestionnaireFlatProto extends
			com.google.protobuf.GeneratedMessage implements
			DataQuestionnaireFlatProtoOrBuilder {
		// Use DataQuestionnaireFlatProto.newBuilder() to construct.
		private DataQuestionnaireFlatProto(Builder builder) {
			super(builder);
		}

		private DataQuestionnaireFlatProto(boolean noInit) {
		}

		private static final DataQuestionnaireFlatProto defaultInstance;

		public static DataQuestionnaireFlatProto getDefaultInstance() {
			return defaultInstance;
		}

		public DataQuestionnaireFlatProto getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProto_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProto_fieldAccessorTable;
		}

		private int bitField0_;
		// required int64 sampleTime = 1;
		public static final int SAMPLETIME_FIELD_NUMBER = 1;
		private long sampleTime_;

		public boolean hasSampleTime() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public long getSampleTime() {
			return sampleTime_;
		}

		// required int64 taskId = 2;
		public static final int TASKID_FIELD_NUMBER = 2;
		private long taskId_;

		public boolean hasTaskId() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public long getTaskId() {
			return taskId_;
		}

		// required int64 actionId = 3;
		public static final int ACTIONID_FIELD_NUMBER = 3;
		private long actionId_;

		public boolean hasActionId() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public long getActionId() {
			return actionId_;
		}

		// required int64 questionId = 4;
		public static final int QUESTIONID_FIELD_NUMBER = 4;
		private long questionId_;

		public boolean hasQuestionId() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public long getQuestionId() {
			return questionId_;
		}

		// required int32 type = 5;
		public static final int TYPE_FIELD_NUMBER = 5;
		private int type_;

		public boolean hasType() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public int getType() {
			return type_;
		}

		// required int64 answerId = 6;
		public static final int ANSWERID_FIELD_NUMBER = 6;
		private long answerId_;

		public boolean hasAnswerId() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		public long getAnswerId() {
			return answerId_;
		}

		// required bool closedAnswerValue = 7;
		public static final int CLOSEDANSWERVALUE_FIELD_NUMBER = 7;
		private boolean closedAnswerValue_;

		public boolean hasClosedAnswerValue() {
			return ((bitField0_ & 0x00000040) == 0x00000040);
		}

		public boolean getClosedAnswerValue() {
			return closedAnswerValue_;
		}

		// required string openAnswerValue = 8;
		public static final int OPENANSWERVALUE_FIELD_NUMBER = 8;
		private java.lang.Object openAnswerValue_;

		public boolean hasOpenAnswerValue() {
			return ((bitField0_ & 0x00000080) == 0x00000080);
		}

		public String getOpenAnswerValue() {
			java.lang.Object ref = openAnswerValue_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					openAnswerValue_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getOpenAnswerValueBytes() {
			java.lang.Object ref = openAnswerValue_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				openAnswerValue_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			sampleTime_ = 0L;
			taskId_ = 0L;
			actionId_ = 0L;
			questionId_ = 0L;
			type_ = 0;
			answerId_ = 0L;
			closedAnswerValue_ = false;
			openAnswerValue_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasSampleTime()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasTaskId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasActionId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasQuestionId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasAnswerId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasClosedAnswerValue()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasOpenAnswerValue()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt64(2, taskId_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt64(3, actionId_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeInt64(4, questionId_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeInt32(5, type_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeInt64(6, answerId_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				output.writeBool(7, closedAnswerValue_);
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				output.writeBytes(8, getOpenAnswerValueBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, sampleTime_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						2, taskId_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						3, actionId_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						4, questionId_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						5, type_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						6, answerId_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				size += com.google.protobuf.CodedOutputStream.computeBoolSize(
						7, closedAnswerValue_);
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						8, getOpenAnswerValueBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProto_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.internal_static_proto_DataQuestionnaireFlatProto_fieldAccessorTable;
			}

			// Construct using
			// it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				sampleTime_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				taskId_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000002);
				actionId_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000004);
				questionId_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000008);
				type_ = 0;
				bitField0_ = (bitField0_ & ~0x00000010);
				answerId_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000020);
				closedAnswerValue_ = false;
				bitField0_ = (bitField0_ & ~0x00000040);
				openAnswerValue_ = "";
				bitField0_ = (bitField0_ & ~0x00000080);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto
						.getDescriptor();
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto getDefaultInstanceForType() {
				return it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto
						.getDefaultInstance();
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto build() {
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto buildPartial() {
				it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto result = new it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.sampleTime_ = sampleTime_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.taskId_ = taskId_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.actionId_ = actionId_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.questionId_ = questionId_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.type_ = type_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000020;
				}
				result.answerId_ = answerId_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000040;
				}
				result.closedAnswerValue_ = closedAnswerValue_;
				if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
					to_bitField0_ |= 0x00000080;
				}
				result.openAnswerValue_ = openAnswerValue_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto) {
					return mergeFrom((it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto other) {
				if (other == it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto
						.getDefaultInstance())
					return this;
				if (other.hasSampleTime()) {
					setSampleTime(other.getSampleTime());
				}
				if (other.hasTaskId()) {
					setTaskId(other.getTaskId());
				}
				if (other.hasActionId()) {
					setActionId(other.getActionId());
				}
				if (other.hasQuestionId()) {
					setQuestionId(other.getQuestionId());
				}
				if (other.hasType()) {
					setType(other.getType());
				}
				if (other.hasAnswerId()) {
					setAnswerId(other.getAnswerId());
				}
				if (other.hasClosedAnswerValue()) {
					setClosedAnswerValue(other.getClosedAnswerValue());
				}
				if (other.hasOpenAnswerValue()) {
					setOpenAnswerValue(other.getOpenAnswerValue());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasSampleTime()) {

					return false;
				}
				if (!hasTaskId()) {

					return false;
				}
				if (!hasActionId()) {

					return false;
				}
				if (!hasQuestionId()) {

					return false;
				}
				if (!hasType()) {

					return false;
				}
				if (!hasAnswerId()) {

					return false;
				}
				if (!hasClosedAnswerValue()) {

					return false;
				}
				if (!hasOpenAnswerValue()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						sampleTime_ = input.readInt64();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						taskId_ = input.readInt64();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						actionId_ = input.readInt64();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						questionId_ = input.readInt64();
						break;
					}
					case 40: {
						bitField0_ |= 0x00000010;
						type_ = input.readInt32();
						break;
					}
					case 48: {
						bitField0_ |= 0x00000020;
						answerId_ = input.readInt64();
						break;
					}
					case 56: {
						bitField0_ |= 0x00000040;
						closedAnswerValue_ = input.readBool();
						break;
					}
					case 66: {
						bitField0_ |= 0x00000080;
						openAnswerValue_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int64 sampleTime = 1;
			private long sampleTime_;

			public boolean hasSampleTime() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public long getSampleTime() {
				return sampleTime_;
			}

			public Builder setSampleTime(long value) {
				bitField0_ |= 0x00000001;
				sampleTime_ = value;
				onChanged();
				return this;
			}

			public Builder clearSampleTime() {
				bitField0_ = (bitField0_ & ~0x00000001);
				sampleTime_ = 0L;
				onChanged();
				return this;
			}

			// required int64 taskId = 2;
			private long taskId_;

			public boolean hasTaskId() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public long getTaskId() {
				return taskId_;
			}

			public Builder setTaskId(long value) {
				bitField0_ |= 0x00000002;
				taskId_ = value;
				onChanged();
				return this;
			}

			public Builder clearTaskId() {
				bitField0_ = (bitField0_ & ~0x00000002);
				taskId_ = 0L;
				onChanged();
				return this;
			}

			// required int64 actionId = 3;
			private long actionId_;

			public boolean hasActionId() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public long getActionId() {
				return actionId_;
			}

			public Builder setActionId(long value) {
				bitField0_ |= 0x00000004;
				actionId_ = value;
				onChanged();
				return this;
			}

			public Builder clearActionId() {
				bitField0_ = (bitField0_ & ~0x00000004);
				actionId_ = 0L;
				onChanged();
				return this;
			}

			// required int64 questionId = 4;
			private long questionId_;

			public boolean hasQuestionId() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public long getQuestionId() {
				return questionId_;
			}

			public Builder setQuestionId(long value) {
				bitField0_ |= 0x00000008;
				questionId_ = value;
				onChanged();
				return this;
			}

			public Builder clearQuestionId() {
				bitField0_ = (bitField0_ & ~0x00000008);
				questionId_ = 0L;
				onChanged();
				return this;
			}

			// required int32 type = 5;
			private int type_;

			public boolean hasType() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public int getType() {
				return type_;
			}

			public Builder setType(int value) {
				bitField0_ |= 0x00000010;
				type_ = value;
				onChanged();
				return this;
			}

			public Builder clearType() {
				bitField0_ = (bitField0_ & ~0x00000010);
				type_ = 0;
				onChanged();
				return this;
			}

			// required int64 answerId = 6;
			private long answerId_;

			public boolean hasAnswerId() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			public long getAnswerId() {
				return answerId_;
			}

			public Builder setAnswerId(long value) {
				bitField0_ |= 0x00000020;
				answerId_ = value;
				onChanged();
				return this;
			}

			public Builder clearAnswerId() {
				bitField0_ = (bitField0_ & ~0x00000020);
				answerId_ = 0L;
				onChanged();
				return this;
			}

			// required bool closedAnswerValue = 7;
			private boolean closedAnswerValue_;

			public boolean hasClosedAnswerValue() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			public boolean getClosedAnswerValue() {
				return closedAnswerValue_;
			}

			public Builder setClosedAnswerValue(boolean value) {
				bitField0_ |= 0x00000040;
				closedAnswerValue_ = value;
				onChanged();
				return this;
			}

			public Builder clearClosedAnswerValue() {
				bitField0_ = (bitField0_ & ~0x00000040);
				closedAnswerValue_ = false;
				onChanged();
				return this;
			}

			// required string openAnswerValue = 8;
			private java.lang.Object openAnswerValue_ = "";

			public boolean hasOpenAnswerValue() {
				return ((bitField0_ & 0x00000080) == 0x00000080);
			}

			public String getOpenAnswerValue() {
				java.lang.Object ref = openAnswerValue_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					openAnswerValue_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setOpenAnswerValue(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000080;
				openAnswerValue_ = value;
				onChanged();
				return this;
			}

			public Builder clearOpenAnswerValue() {
				bitField0_ = (bitField0_ & ~0x00000080);
				openAnswerValue_ = getDefaultInstance().getOpenAnswerValue();
				onChanged();
				return this;
			}

			void setOpenAnswerValue(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000080;
				openAnswerValue_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:proto.DataQuestionnaireFlatProto)
		}

		static {
			defaultInstance = new DataQuestionnaireFlatProto(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:proto.DataQuestionnaireFlatProto)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataQuestionnaireFlatProtoList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataQuestionnaireFlatProtoList_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_proto_DataQuestionnaireFlatProto_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_proto_DataQuestionnaireFlatProto_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n!DataQuestionnaireFlatProtos.proto\022\005pro"
				+ "to\"Q\n\036DataQuestionnaireFlatProtoList\022/\n\004"
				+ "list\030\001 \003(\0132!.proto.DataQuestionnaireFlat"
				+ "Proto\"\272\001\n\032DataQuestionnaireFlatProto\022\022\n\n"
				+ "sampleTime\030\001 \002(\003\022\016\n\006taskId\030\002 \002(\003\022\020\n\010acti"
				+ "onId\030\003 \002(\003\022\022\n\nquestionId\030\004 \002(\003\022\014\n\004type\030\005"
				+ " \002(\005\022\020\n\010answerId\030\006 \002(\003\022\031\n\021closedAnswerVa"
				+ "lue\030\007 \002(\010\022\027\n\017openAnswerValue\030\010 \002(\tB@\n!it"
				+ ".unibo.participact.domain.protoB\033DataQue"
				+ "stionnaireFlatProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_proto_DataQuestionnaireFlatProtoList_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_proto_DataQuestionnaireFlatProtoList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataQuestionnaireFlatProtoList_descriptor,
						new java.lang.String[] { "List", },
						it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList.class,
						it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProtoList.Builder.class);
				internal_static_proto_DataQuestionnaireFlatProto_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_proto_DataQuestionnaireFlatProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_proto_DataQuestionnaireFlatProto_descriptor,
						new java.lang.String[] { "SampleTime", "TaskId",
								"ActionId", "QuestionId", "Type", "AnswerId",
								"ClosedAnswerValue", "OpenAnswerValue", },
						it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.class,
						it.unibo.participact.domain.proto.DataQuestionnaireFlatProtos.DataQuestionnaireFlatProto.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
